name: Test

on:
  push:
    branches: ["main", $default-branch]
  pull_request:
    branches: ["main", $default-branch]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          yarn install
          yarn docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: ./packages/@no-day/docs/public
